name: Handle PR Comment Webhook

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:  # Allows manual workflow level trigger
    inputs:
      comment_body:
        description: 'Body of the commit suggestion'
        required: true
        type: string
      comment_line:
        description: 'Start line number of the comment'
        required: true
        type: string
      comment_file_path:
        description: 'File path of the file in which commit suggestion was made'
        required: true
        type: string

jobs:
  process-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Apply commit suggestion
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.comment_body != null && github.event.inputs.comment_line != null & github.event.inputs.comment_file_path != null
        run: |
          echo "Suggestion code : ${{ github.event.inputs.comment_body }}"
          echo "Start line : ${{ github.event.inputs.comment_line }}"
          echo "File path : ${{ github.event.inputs.comment_file_path }}"
          # Execute script
          python generate-patch.py --suggestion ${{ github.event.inputs.comment_body }} --line ${{ github.event.inputs.comment_line }} --filepath ${{ github.event.inputs.comment_file_path }}
          echo Patch generated at suggestion.patch
          cat suggestion.patch
          # Apply patch
          git apply suggestion.patch
          echo Patch successfully applied

      - name: Run tests
        run: |
          # Run tests
          python -m unittest discover test
