name: Handle PR Comment Webhook

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual workflow level trigger
    inputs:
      commit_suggestions:
        description: 'Encoded list of commit suggestions'
        required: true
        type: string

jobs:
  process-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Apply commit suggestion
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.comment_body != null && github.event.inputs.comment_line != null && github.event.inputs.comment_file_path != null
        run: |
          echo "Triggering patch file generation for received commit suggestions"
          # Execute script
          python generate-patch.py --comments ${{ github.event.inputs.commit_suggestions }}
          # List all generated patch files
          ls patches
          # Apply all patch files
          for patch in patches/*.patch; do git apply "$patch" && echo "Patch applied successfully - $patch"; done

      - name: Run tests
        run: |
          # Run tests
          python -m unittest discover test
