name: Handle PR Comment Webhook

on:
  workflow_dispatch:  # Allows manual workflow level trigger
    inputs:
      comment_body:
        description: 'Body of the commit suggestion'
        required: true
        type: string
      comment_line:
        description: 'Start line number of the comment'
        required: true
        type: string
      comment_file_path:
        description: 'File path of the file in which commit suggestion was made'
        required: true
        type: string
  repository_dispatch: # Allows repository level trigger
    types: [pr_comment_added]

jobs:
  process-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Comment Details
        run: |
          echo "Suggestion code : ${{ github.event.inputs.comment_body }}"
          echo "Start line : ${{ github.event.inputs.comment_line }}"
          echo "File path : ${{ github.event.inputs.comment_file_path }}"